### ISSUE TITLE
FR: 使用后的一些改进建议

### ISSUE THREAD

**Issue by YIRU69** [luhaifeng666/obsidian-text2audio#20]
您好，作者，我一直有 tts 的需求，正好发现了您的这个插件，真是太感谢您了。

在使用的过程中，我发现了可能改进的点

1. 关于语音的选择和配置。每次生成语音都需要重新选择，是否可以有历史记录，或者增加自定义的配置，这样方便切换和使用。
2. 关于文件命名的方案。是否可以根据文件名+定义的前缀后缀+数字的方式的批量命名。
3. 增加批量生成的功能。是否可以通过行的分隔，来批量生成语音。这样的话语音窗口是否可以修改成 tab 标签页的形式，这样也可以配合文件批量命名。
4. 增加语音文件自动嵌入。有一个场景是，当我选择了一行文字，运行插件，插件会自动生成语音（根据自己之前保存再配置），然后在这个句子的下一行，或者后面嵌入“![[xxx.mp3]]”.
5. 增加对文字的处理。当文字中有特定的符号和格式的时候，比如有"_",那么这个符号就会被直接读出现。是否可以增加对特定符号的滤除，当时最好还是可以支持正则，这样也可以有多种玩法了。

**Comment by YIRU69** [comment]
另外我发现音频的格式，对于保存的音频，好像不起作用，都是 wav 的格式

**Comment by luhaifeng666** [comment]
> 您好，作者，我一直有 tts 的需求，正好发现了您的这个插件，真是太感谢您了。
> 
> 在使用的过程中，我发现了可能改进的点
> 
> 1. 关于语音的选择和配置。每次生成语音都需要重新选择，是否可以有历史记录，或者增加自定义的配置，这样方便切换和使用。
> 2. 关于文件命名的方案。是否可以根据文件名+定义的前缀后缀+数字的方式的批量命名。
> 3. 增加批量生成的功能。是否可以通过行的分隔，来批量生成语音。这样的话语音窗口是否可以修改成 tab 标签页的形式，这样也可以配合文件批量命名。
> 4. 增加语音文件自动嵌入。有一个场景是，当我选择了一行文字，运行插件，插件会自动生成语音（根据自己之前保存再配置），然后在这个句子的下一行，或者后面嵌入“![[xxx.mp3]]”.
> 5. 增加对文字的处理。当文字中有特定的符号和格式的时候，比如有"_",那么这个符号就会被直接读出现。是否可以增加对特定符号的滤除，当时最好还是可以支持正则，这样也可以有多种玩法了。

您好：

首先感谢您的使用，以及您的宝贵建议~

关于第1/4/5三点，我近期会优先优化。至于批量生成的功能，我这边再考虑下实现的方案，短期内可能暂时不会支持。

另外，关于音频格式的问题，我也会在近期一并优化。

再次感谢您的支持~

**Comment by YIRU69** [comment]
文件的命名希望也能做一下

**Comment by luhaifeng666** [comment]
> 文件的命名希望也能做一下

短期内暂时仅支持单个音频文件的生成，文件名称还是依赖手动输入，因为文件格式可能因人而异，所以暂时不做调整。关于这一点还请理解~

**Comment by YIRU69** [comment]
> 短期内暂时仅支持单个音频文件的生成，文件名称还是依赖手动输入，因为文件格式可能因人而异，所以暂时不做调整。关于这一点还请理解~

单个文件命名可以默认提取标题也可以呀，或者默认的创建时间自动命名。。。

这样我生成多个文件用其他的工具统一重命名

**Comment by luhaifeng666** [comment]
> > 短期内暂时仅支持单个音频文件的生成，文件名称还是依赖手动输入，因为文件格式可能因人而异，所以暂时不做调整。关于这一点还请理解~
> 
> 单个文件命名可以默认提取标题也可以呀，或者默认的创建时间自动命名。。。
> 
> 这样我生成多个文件用其他的工具统一重命名

默认文件名的提议倒是不错，这个我改进下，感谢~

**Comment by lvxiaoc** [comment]
非常好用的功能。谢谢。楼主提的东西也很好，
1.每次都要选择语言生成选项是很致命的，应该能够保存默认选项。
2.obsidian应该只作为编辑思考时候使用的环境，所以生成多段语音功能不是很重要，可以在写好稿子之后进入微软的speech studio操作即可。
3.将重点放在如何尽量少的打断思考创作流程上面，一键倾听自己选中的内容，或者没有选择文本的时候一键倾听光标所在的段落内容，如果能做到这点就最好了。我现在基本上是直接在speech studio里面创作，有点遗憾不能用obsidian来书写。
再次感谢作者的奉献！

**Comment by luhaifeng666** [comment]
> 非常好用的功能。谢谢。楼主提的东西也很好， 1.每次都要选择语言生成选项是很致命的，应该能够保存默认选项。 2.obsidian应该只作为编辑思考时候使用的环境，所以生成多段语音功能不是很重要，可以在写好稿子之后进入微软的speech studio操作即可。 3.将重点放在如何尽量少的打断思考创作流程上面，一键倾听自己选中的内容，或者没有选择文本的时候一键倾听光标所在的段落内容，如果能做到这点就最好了。我现在基本上是直接在speech studio里面创作，有点遗憾不能用obsidian来书写。 再次感谢作者的奉献！

收到~
感谢您的支持与反馈~

**Comment by lvxiaoc** [comment]
作者更新真快。一键朗读功能已经实现了，非常好用，谢谢。唯一略觉要中断写作过程的就是“选中文本”然后朗读的设计。如果在没有选中文本时候，能够默认朗读光标所在段落，甚至所在的句子（可选）就好了，这样，就做到了最低程度的对创作过程的打扰。毕竟选择文本也是一个多余的动作。

**Comment by luhaifeng666** [comment]
> 作者更新真快。一键朗读功能已经实现了，非常好用，谢谢。唯一略觉要中断写作过程的就是“选中文本”然后朗读的设计。如果在没有选中文本时候，能够默认朗读光标所在段落，甚至所在的句子（可选）就好了，这样，就做到了最低程度的对创作过程的打扰。毕竟选择文本也是一个多余的动作。

感谢支持~

这个功能已经在考虑实现了，近期会搞定~
