### ISSUE TITLE
无法保存语音，无法插入已生成语音

### ISSUE THREAD

**Issue by anging** [luhaifeng666/obsidian-text2audio#47]
# 问题描述

1，无法保存语音：
设置文件名和默认都无法保存，提示no such file or path 
后台已设置保存路径
![02](https://github.com/luhaifeng666/obsidian-text2audio/assets/10354675/5212e6c3-ccc9-47e4-97ce-7d6a4009c8df)

2，无法插入已生成语音
开启interposition后也无法在光标处插入生成文件

# 环境信息

- Obsidian 版本:1.5.12

- 当前操作系统:Windows 10 专业版  22H2
- Text2Audio 插件版本:1.12.1
- Text2Audio 插件配置(注意: `不需要提供 Speech Key 以及 Speech region!!! 请注意保护自己的数据安全!!`):
![01](https://github.com/luhaifeng666/obsidian-text2audio/assets/10354675/e0e01d98-017c-4b21-ab81-c7c2f65c8724)

**Comment by xujialiu** [comment]
报错信息显示没有找到对应的文件, 请使用绝对路径, 并确保该路径有效.
比如说想把路径设置为c盘下的`阅读`文件夹, 请在确保c盘目录下创建`阅读`文件夹后, 将设置的Directory设为: `C:\阅读`

**Comment by anging** [comment]
> 报错信息显示没有找到对应的文件, 请使用绝对路径, 并确保该路径有效. 比如说想把路径设置为c盘下的`阅读`文件夹, 请在确保c盘目录下创建`阅读`文件夹后, 将设置的Directory设为: `C:\阅读`

谢谢，使用绝对路径后问题已解决。
