### ISSUE TITLE
Suggestion: 将play和pause快捷键合并成1个play/pause快捷键

### ISSUE THREAD

**Issue by xujialiu** [luhaifeng666/obsidian-text2audio#49]
![image](https://github.com/luhaifeng666/obsidian-text2audio/assets/46064313/fd0a1190-b563-45ec-9aa0-ce2ec9a64045)

play和pause是经常用到的快捷键, 对于大部分播放器而已, 它们都被设计成1个按键, 将play和pause分开会使得使用上的割裂感, 能否将原来的2个快捷键集成为一个play/pause快捷键, 谢谢.

**Comment by xujialiu** [comment]
抱歉, 我的描述可能有点问题, 我的意思是Text2Audio: Pause the audio和Text2Audio: Resume the audio最好是能绑定成一个快捷键, 并通过播放器的状态自动判断是应该使用Pause功能还是使用Resume功能, 再次感谢作者的付出, 谢谢.

**Comment by luhaifeng666** [comment]
> 抱歉, 我的描述可能有点问题, 我的意思是Text2Audio: Pause the audio和Text2Audio: Resume the audio最好是能绑定成一个快捷键, 并通过播放器的状态自动判断是应该使用Pause功能还是使用Resume功能, 再次感谢作者的付出, 谢谢.

嗯嗯，我理解你的意思。确实是个不错的建议~
感谢支持与反馈~

**Comment by xujialiu** [comment]
> > 抱歉, 我的描述可能有点问题, 我的意思是Text2Audio: Pause the audio和Text2Audio: Resume the audio最好是能绑定成一个快捷键, 并通过播放器的状态自动判断是应该使用Pause功能还是使用Resume功能, 再次感谢作者的付出, 谢谢.
> 
> 嗯嗯，我理解你的意思。确实是个不错的建议~ 感谢支持与反馈~

我觉得可以增加一个Text2Audio: Cancel the audio快捷键, 然后将Text2Audio: Pause the audio和Text2Audio: Resume the audio合并成一个. 当按下Text2Audio: Cancel the audio快捷键时, 结束语音播放的进程. 这样是不是可以一定程度上解决多次按下Text2Audio: Convert text to speech快捷键时会有多个声音的bug?

**Comment by luhaifeng666** [comment]
> > > 抱歉, 我的描述可能有点问题, 我的意思是Text2Audio: Pause the audio和Text2Audio: Resume the audio最好是能绑定成一个快捷键, 并通过播放器的状态自动判断是应该使用Pause功能还是使用Resume功能, 再次感谢作者的付出, 谢谢.
> > 
> > 
> > 嗯嗯，我理解你的意思。确实是个不错的建议~ 感谢支持与反馈~
> 
> 我觉得可以增加一个Text2Audio: Cancel the audio快捷键, 然后将Text2Audio: Pause the audio和Text2Audio: Resume the audio合并成一个. 当按下Text2Audio: Cancel the audio快捷键时, 结束语音播放的进程. 这样是不是可以一定程度上解决多次按下Text2Audio: Convert text to speech快捷键时会有多个声音的bug?

其实在创建一段新的语音的时候，上一个进程就可以杀掉了，我应该是把这个做漏掉了。

**Comment by luhaifeng666** [comment]
支持版本：2.0.0
BREAKING CHANGE: 合并两个指令为一个指令： `Pause or resume the audio`
