### ISSUE TITLE
Improvement: Text formatting设置的描述太过笼统, 应该明确的写成Text RegEx formating

### ISSUE THREAD

**Issue by xujialiu** [luhaifeng666/obsidian-text2audio#51]
![image](https://github.com/luhaifeng666/obsidian-text2audio/assets/46064313/f0262ed5-a7a6-49bd-8761-58c55ce2497e)
如题, Text formatting设置的描述太过笼统, 我自己试了好多次, 最开始是用空格, 然后是用`,`, 最后去查看了源码才知道这个设置是直接用正则表达式替换, 希望作者能改进一下这个部分的描述, 并给一个example, 谢谢

**Comment by xujialiu** [comment]
另外, 通常正则表达式都是挺长的, 这里给的空间似乎有点狭窄, 推荐类似pandoc插件那样把输入框的高度增加一些, 然后把示例放到输入框中, 谢谢作者.
![image](https://github.com/luhaifeng666/obsidian-text2audio/assets/46064313/911a258f-c701-4eff-8400-ba3b9d6f0b76)

**Comment by luhaifeng666** [comment]
其实目前这种实现方式有点粗糙，而且不太友好，对于非程序员用户而言存在使用门槛。后面我可能会换种实现方式。在此之前可以按照你的建议去做修改~
再次感谢反馈~

**Comment by luhaifeng666** [comment]
支持版本：2.1.0
功能调整：文本过滤配置项优化，输入框改为文本域，支持自定义伸缩尺寸，并优化暗纹提示。
