### ISSUE TITLE
Bug: Interposition设置似乎没有生效

### ISSUE THREAD

**Issue by xujialiu** [luhaifeng666/obsidian-text2audio#52]
问题描述:
![image](https://github.com/luhaifeng666/obsidian-text2audio/assets/46064313/0f672d2b-b5ef-448f-8056-5a8c3f661c34)

根据这个设置, 我的理解是当enabled时, Text2Audio: Convert text to speech, 文本转语音是从光标的位置开始, 阅读文本到最后一行, 也坑呢是我的理解不对.

不过如果这个设置不是我描述的那样, 希望作者增加一个快捷键
设置名: Text2Audio: Read text util end
快捷键功能描述: 当按下这个快捷键时, 从光标位置一直读到文本的结尾.

谢谢作者!

环境信息:

Obsidian 版本: v1.5.12
当前操作系统: windows 11
Text2Audio 插件版本: 1.12.1

**Comment by luhaifeng666** [comment]
这个配置是用来决定是否将生成的语音文件插入到光标所在的位置的。
关于你提到的功能，目前有一项对应的配置，不过是在没有选择文本是，阅读光标之前的所有内容：
![image](https://github.com/luhaifeng666/obsidian-text2audio/assets/9375823/f6ea4dfe-8726-4123-8378-8d04ba4372c8)
根据你的建议，近期我会优化这项配置，用于选择阅读光标前还是光标后的内容。

**Comment by luhaifeng666** [comment]
支持版本：2.2.0
修改内容：修改原先的 `Read Previous` 选项为 `Read before or after`, 用于支持阅读光标后的内容。
