### ISSUE TITLE
Bug: 设置中的Language选项没有作用, 建议去除

### ISSUE THREAD

**Issue by xujialiu** [luhaifeng666/obsidian-text2audio#56]
# 问题描述
![image](https://github.com/luhaifeng666/obsidian-text2audio/assets/46064313/b8f13842-6897-487f-9560-5ea25b73a467)

设置中的Language选项似乎没有起作用, 一开始我以为是设置语音的语言, 但是实验了一下, 只有播放界面的Language type有效, 我尝试手动删除`var SETTINGS`对象里的Language, 似乎对程序没有任何影响, 是不是可以考虑去掉这个选项,  因为这个选项, 会给用户带来困惑, 谢谢.

环境信息:

Obsidian 版本: v1.5.12
当前操作系统: windows 11
Text2Audio 插件版本: 2.0.0

**Comment by xujialiu** [comment]
好吧, 我发现是按下Text2Audio: Convert text to speech后提示框的language, 建议把hint改成: Select the message popup language, 这样不容易造成歧义, 如果后续添加新的功能, 再修改hint即可, 谢谢.

**Comment by luhaifeng666** [comment]
这个是用来设置整个插件的语言的，不只是提示框，弹窗里的文案在切换后也会发生变化。可以理解为一个简易的语言包。
![image](https://github.com/luhaifeng666/obsidian-text2audio/assets/9375823/eb683cda-09ba-4fe5-90e6-52232b389e16)
