### ISSUE TITLE
Bug: 播放后Convert text to speech快捷键无响应

### ISSUE THREAD

**Issue by xujialiu** [luhaifeng666/obsidian-text2audio#60]
# 问题描述

设置如下
![image](https://github.com/luhaifeng666/obsidian-text2audio/assets/46064313/2d947abf-1780-4dd0-8aec-a69bb31c6cb7)

当按下Text2Audio: Convert text to speech快捷键, 播放器会从cursor处开始朗读文本. 

1. 如果在朗读过程中, 把鼠标光标放到另一个地方(没有暂停), 再按下Text2Audio: Convert text to speech快捷键, 此时, 原来的播放器不会取消, 且不会重新开始读取文本, 播放器会处于无响应状态

2. 但如果在朗读的过程中, 按下Text2Audio: Pause or resume the audio, 此时, 播放器会暂停, 但如果此时将cursor放到其他地方(播放器处于暂停状态), 再按下Text2Audio: Convert text to speech快捷键, 播放器也会变得无响应.

这2个问题使得如果要重新播放某段文本变得不可能, 希望作者能修复这个bug

最后再感谢作者这两天来对我之前提出的issues的快速修复, 谢谢

# 环境信息

Obsidian 版本: v1.5.12
当前操作系统: windows 11
Text2Audio 插件版本: 2.2.0

**Comment by xujialiu** [comment]
有一个比较快速的解决办法: 提供一个cancel the speech快捷键, 这样如果出现无响应的情况, 点击一下这个快捷键
目前, 我是将Auto Stop选项打开, 然后把open tab快捷键当作cancel the speech快捷键, 来暂时解决播放器无响应的问题

另外一种解决方法是, 就需要修改一下Text2Audio: Convert text to speech快捷键的逻辑, 让其能在播放和暂停状态下关闭当前播放器进程, 并启动一个新的播放器进程

**Comment by luhaifeng666** [comment]
在使用Convert text to speech 指令的时候，右上角有弹出 Converting 的 toast 提示么？
这两个问题我都试了下，没有复现你所之处的问题。我实验的系统是 MacOs, 晚上回去我换成 Windows 试试。

**Comment by luhaifeng666** [comment]
> 在使用Convert text to speech 指令的时候，右上角有弹出 Converting 的 toast 提示么？ 这两个问题我都试了下，没有复现你所之处的问题。我实验的系统是 MacOs, 晚上回去我换成 Windows 试试。

试了下，windows上确实有这个问题。

**Comment by luhaifeng666** [comment]
支持版本：2.2.1
