### ISSUE TITLE
Bug: 2.2.1似乎没有修复60#issue

### ISSUE THREAD

**Issue by xujialiu** [luhaifeng666/obsidian-text2audio#62]
作者你好, 我升级到2.2.1后60#issue汇报的bug, 在windows上依旧存在

- Obsidian 版本: v1.5.12
- 当前操作系统: windows 11
- Text2Audio 插件版本: 2.2.0

**Comment by xujialiu** [comment]
我又详细地测试了一下.

具体的说, 应该是如果按下Text2Audio: Convert text to speech快捷键, 此时正常播放, 如果在25秒内将光标移动到其他位置, 在点击Text2Audio: Convert text to speech快捷键, 此时没有反应, 但是播放25秒后可以

之前好像是不管过多久都不行

**Comment by luhaifeng666** [comment]
> 我又详细地测试了一下.
> 
> 具体的说, 应该是如果按下Text2Audio: Convert text to speech快捷键, 此时正常播放, 如果在25秒内将光标移动到其他位置, 在点击Text2Audio: Convert text to speech快捷键, 此时没有反应, 但是播放25秒后可以
> 
> 之前好像是不管过多久都不行

两次光标移动的位置一样么？光标后有内容么？

**Comment by xujialiu** [comment]
我发现如果按下Text2Audio: Convert text to speech快捷键后, 右上角会先出现"转换中...."的提示, 此时播放器已经开始播放, 然后, 过一段时间(我测试约20多秒)才会出现"语音合成成功"的提示

如果在播放器开始播放后, 但没有出现"语音合成成功"的提示之前, 按下Text2Audio: Convert text to speech快捷键, 就会没有反应

如果在出现"语音合成成功"的提示之后按下Text2Audio: Convert text to speech快捷键, 就能正常开始下一段播放.

麻烦作者测试一下是不是有这种情况.

**Comment by xujialiu** [comment]
> > 我又详细地测试了一下.
> > 具体的说, 应该是如果按下Text2Audio: Convert text to speech快捷键, 此时正常播放, 如果在25秒内将光标移动到其他位置, 在点击Text2Audio: Convert text to speech快捷键, 此时没有反应, 但是播放25秒后可以
> > 之前好像是不管过多久都不行
> 
> 两次光标移动的位置一样么？光标后有内容么？

光标无论移动或是不移动, 都有这种情况.

**Comment by luhaifeng666** [comment]
> 我发现如果按下Text2Audio: Convert text to speech快捷键后, 右上角会先出现"转换中...."的提示, 此时播放器已经开始播放, 然后, 过一段时间(我测试约20多秒)才会出现"语音合成成功"的提示
> 
> 如果在播放器开始播放后, 但没有出现"语音合成成功"的提示之前, 按下Text2Audio: Convert text to speech快捷键, 就会没有反应
> 
> 如果在出现"语音合成成功"的提示之后按下Text2Audio: Convert text to speech快捷键, 就能正常开始下一段播放.
> 
> 麻烦作者测试一下是不是有这种情况.

这是因为语音没有转换完成，所以无法播放。因为转换的内容比较多，所以需要耗费一些时间。
当语音合成成功提示出现时，说明语音转换完成，此时才可以播放。
这种交互在弹窗里会比较明显。

**Comment by xujialiu** [comment]
> > 我发现如果按下Text2Audio: Convert text to speech快捷键后, 右上角会先出现"转换中...."的提示, 此时播放器已经开始播放, 然后, 过一段时间(我测试约20多秒)才会出现"语音合成成功"的提示
> > 如果在播放器开始播放后, 但没有出现"语音合成成功"的提示之前, 按下Text2Audio: Convert text to speech快捷键, 就会没有反应
> > 如果在出现"语音合成成功"的提示之后按下Text2Audio: Convert text to speech快捷键, 就能正常开始下一段播放.
> > 麻烦作者测试一下是不是有这种情况.
> 
> 这是因为语音没有转换完成，所以无法播放。因为转换的内容比较多，所以需要耗费一些时间。 当语音合成成功提示出现时，说明语音转换完成，此时才可以播放。 这种交互在弹窗里会比较明显。

哦哦, 好的, 那之前的bug确实是被2.2.1解决了. 为了避免出现类似的issue, 建议作者在设置的Read before or after的描述中, 加上类似这样的提示: 如果文本过长, 需要等待文本完全转换成语音后才能进行下一次文本转语音的操作.

最后, 感谢作者大大修复bug一如既往的快, 谢谢

**Comment by luhaifeng666** [comment]
> > > 我发现如果按下Text2Audio: Convert text to speech快捷键后, 右上角会先出现"转换中...."的提示, 此时播放器已经开始播放, 然后, 过一段时间(我测试约20多秒)才会出现"语音合成成功"的提示
> > > 如果在播放器开始播放后, 但没有出现"语音合成成功"的提示之前, 按下Text2Audio: Convert text to speech快捷键, 就会没有反应
> > > 如果在出现"语音合成成功"的提示之后按下Text2Audio: Convert text to speech快捷键, 就能正常开始下一段播放.
> > > 麻烦作者测试一下是不是有这种情况.
> > 
> > 
> > 这是因为语音没有转换完成，所以无法播放。因为转换的内容比较多，所以需要耗费一些时间。 当语音合成成功提示出现时，说明语音转换完成，此时才可以播放。 这种交互在弹窗里会比较明显。
> 
> 哦哦, 好的, 那之前的bug确实是被2.2.1解决了. 为了避免出现类似的issue, 建议作者在设置的Read before or after的描述中, 加上类似这样的提示: 如果文本过长, 需要等待文本完全转换成语音后才能进行下一次文本转语音的操作.
> 
> 最后, 感谢作者大大修复bug一如既往的快, 谢谢

我优化下提示的消失时间吧，等结束之后再消失，没结束的时候不消失。

**Comment by luhaifeng666** [comment]
> > > 我发现如果按下Text2Audio: Convert text to speech快捷键后, 右上角会先出现"转换中...."的提示, 此时播放器已经开始播放, 然后, 过一段时间(我测试约20多秒)才会出现"语音合成成功"的提示
> > > 如果在播放器开始播放后, 但没有出现"语音合成成功"的提示之前, 按下Text2Audio: Convert text to speech快捷键, 就会没有反应
> > > 如果在出现"语音合成成功"的提示之后按下Text2Audio: Convert text to speech快捷键, 就能正常开始下一段播放.
> > > 麻烦作者测试一下是不是有这种情况.
> > 
> > 
> > 这是因为语音没有转换完成，所以无法播放。因为转换的内容比较多，所以需要耗费一些时间。 当语音合成成功提示出现时，说明语音转换完成，此时才可以播放。 这种交互在弹窗里会比较明显。
> 
> 哦哦, 好的, 那之前的bug确实是被2.2.1解决了. 为了避免出现类似的issue, 建议作者在设置的Read before or after的描述中, 加上类似这样的提示: 如果文本过长, 需要等待文本完全转换成语音后才能进行下一次文本转语音的操作.
> 
> 最后, 感谢作者大大修复bug一如既往的快, 谢谢

哈哈哈，非常感谢你这段时间的建议跟耐心反馈~~~
