### ISSUE TITLE
Feature request: 请求增加一个cancel the audio的快捷键

### ISSUE THREAD

**Issue by xujialiu** [luhaifeng666/obsidian-text2audio#64]
问题描述
如[issue #62](https://github.com/luhaifeng666/obsidian-text2audio/issues/62), 如果设定是read after, 且文本过长, 文本转语音可能需要一段时间, 如果此时先取消文本, 从另一个地方开始, 只能打开auto stop, 通过打开其他tab的方式取消播放. 

此外, 从快捷键的逻辑上讲, 目前的快捷键有`开始播放`, `暂停和恢复`, 却没有`停止播放`选项, 有点奇怪. 

加上`停止选项`后, 快捷键的播放器控制逻辑才算完整.

希望作者能采纳这个建议, 谢谢.

**Comment by luhaifeng666** [comment]
这个诉求是终止语音转换是吧。我回头加上~
目前这个功能仅有弹窗支持。

**Comment by xujialiu** [comment]
> 这个诉求是终止语音转换是吧。我回头加上~ 目前这个功能仅有弹窗支持。

终止语音转换的同时终止播放器进程, 这样比较合理

另外, 作者你的更新频率和发布周期是真的快, respect!

**Comment by xujialiu** [comment]
> > 这个诉求是终止语音转换是吧。我回头加上~ 目前这个功能仅有弹窗支持。
> 
> 终止语音转换的同时终止播放器进程, 这样比较合理
> 
> 另外, 作者你的更新频率和发布周期是真的快, respect!

另外, #68 中提到的auto stop, 也应该是终止语音转换的同时终止播放器进程, 感谢作者采纳建议, 谢谢

**Comment by luhaifeng666** [comment]
> > 这个诉求是终止语音转换是吧。我回头加上~ 目前这个功能仅有弹窗支持。
> 
> 终止语音转换的同时终止播放器进程, 这样比较合理
> 
> 另外, 作者你的更新频率和发布周期是真的快, respect!

嗯嗯，终止转换的同时，我会销毁当前实例的。
哈哈哈哈，有空就会来折腾折腾，如果忙的话就会耽搁几天。

**Comment by xujialiu** [comment]
> > > 这个诉求是终止语音转换是吧。我回头加上~ 目前这个功能仅有弹窗支持。
> > 
> > 
> > 终止语音转换的同时终止播放器进程, 这样比较合理
> > 另外, 作者你的更新频率和发布周期是真的快, respect!
> 
> 嗯嗯，终止转换的同时，我会销毁当前实例的。 哈哈哈哈，有空就会来折腾折腾，如果忙的话就会耽搁几天。

嗯嗯, 太感谢你的维护和支持了, 如果未来要引入python相关功能, 我很乐意帮忙一起维护, 不过js和ts是真的没学过, 无法帮忙.

另外, 我觉得插件的引导可能需要写得跟详尽一些, 原来的引导有点模糊, 可能会劝退一些不大想折腾的用户, 而且近期加入了很多新的功能.

新的引导麻烦交给我来写, 我也想为这个插件贡献, 哈哈哈.

**Comment by luhaifeng666** [comment]
> > > > 这个诉求是终止语音转换是吧。我回头加上~ 目前这个功能仅有弹窗支持。
> > > 
> > > 
> > > 终止语音转换的同时终止播放器进程, 这样比较合理
> > > 另外, 作者你的更新频率和发布周期是真的快, respect!
> > 
> > 
> > 嗯嗯，终止转换的同时，我会销毁当前实例的。 哈哈哈哈，有空就会来折腾折腾，如果忙的话就会耽搁几天。
> 
> 嗯嗯, 太感谢你的维护和支持了, 如果未来要引入python相关功能, 我很乐意帮忙一起维护, 不过js和ts是真的没学过, 无法帮忙.
> 
> 另外, 我觉得插件的引导可能需要写得跟详尽一些, 原来的引导有点模糊, 可能会劝退一些不大想折腾的用户, 而且近期加入了很多新的功能.
> 
> 新的引导麻烦交给我来写, 我也想为这个插件贡献, 哈哈哈.

可以呀~你可以 Fork 一份，改完了提 PR 就好~
非常感谢~

**Comment by luhaifeng666** [comment]
> > > 这个诉求是终止语音转换是吧。我回头加上~ 目前这个功能仅有弹窗支持。
> > 
> > 
> > 终止语音转换的同时终止播放器进程, 这样比较合理
> > 另外, 作者你的更新频率和发布周期是真的快, respect!
> 
> 另外, #68 中提到的auto stop, 也应该是终止语音转换的同时终止播放器进程, 感谢作者采纳建议, 谢谢

这个开关的作用是在打开新的窗口的时候，暂停正在播放的语音用的，其目的并不是为了阻止语音生成。

**Comment by luhaifeng666** [comment]
支持版本：2.6.0
功能调整：新增指令：Stop conversion， 用于终止语音生成。
