### ISSUE TITLE
Feature request: Read before or after增加一个`None`选项

### ISSUE THREAD

**Issue by xujialiu** [luhaifeng666/obsidian-text2audio#65]
![image](https://github.com/luhaifeng666/obsidian-text2audio/assets/46064313/ea5f4a2a-d003-4b0e-bd7a-a1383e94e548)
Read before or after是一个很好的选项, 但考虑到如果文本很长, 误触快捷键会导致浪费Azure的时长, `None`的意义在于, 对于那些长文本的note, 强制用户使用选择文本后再按下Text2Audio: Convert text to audio快捷键, 如果用户误触快捷键, 则不会转换.

实现这个应该很简单, 就是之前取消read before选项的逻辑而已, 希望作者能采纳这个建议, 谢谢.

**Comment by luhaifeng666** [comment]
支持版本：2.4.0
功能调整：Read before or after 配置新增 `Off` 选项，用于关闭此功能。
