### ISSUE TITLE
Improvement: 关于auto stop的逻辑优化

### ISSUE THREAD

**Issue by xujialiu** [luhaifeng666/obsidian-text2audio#68]
对于长文本而已, 如果设置为read after, 点击Text2Audio: Convert text to speech快捷键后, 右上角会先出现`Converting...`, 等过一会儿才会出现`Synthesis finished.`提示.

如果在打开auto stop设置选项的下, 在`Converting...`出现后, 且还未出现`Synthesis finished.`前, 打开或关闭一个tab, 此时播放器会停止, 这里没有问题, 但问题是文本转语音的进程似乎依旧在后台进行, 因为此时, 右上角`Converting...`选项依旧在. 如果在这是点击Text2Audio: Convert text to speech快捷键, 是没有反应的. 只有等`Converting...`消失, 并显示`Synthesis finished.`后, 才能进行Convert text to speech快捷键的操作.

我的理解是, 当打开或关闭一个tab时, 播放器进程被结束, 但是文本转语音的进程仍然在进行, 因此如果这时当按下Text2Audio: Convert text to speech快捷键, 由于进程阻塞的原因, 会导致无响应, 只有等进程被释放后才能进行Convert text to speech快捷键的操作.

因此能不能对auto stop的选项优化一下, 让它在结束播放器进程的同时, 终止文本转语音的进程.

希望作者能才能这个优化方案, 谢谢

Obsidian 版本: v1.5.12
当前操作系统: windows 11
Text2Audio 插件版本: 2.4.0

**Comment by luhaifeng666** [comment]
支持版本：2.7.0
功能调整：更改Auto Stop为Auto Pause, 并将Auto Stop配置的功能调整为,在打开或关闭笔记的时候,终止语音转换。
