### ISSUE TITLE
Feature request: 增加一个跳过codeblock的选项

### ISSUE THREAD

**Issue by xujialiu** [luhaifeng666/obsidian-text2audio#74]
我尝试用设置的Text formatting来设置跳过codeblock, 不过这个正则表达式好像没有开启Single-line Mode

能否增加个跳过codeblock的选项或是增加个开启Single-line Mode的Text formatting设置. 

希望这个建议能被采纳, 感谢作者的开发和维护, 谢谢!

**Comment by xujialiu** [comment]
其实我觉得最好的方式也把Text formatting的`Regex flags`选项交给用户, 但是如果放在设置中, 会导致需要太多的设置checkbox, 而且这个功能可能只有少部分人会编程的人会用到.

所以我建议, 在data.json中把是否打开Text formatting的Regex flags的选项交给用户自己选择, 然后, 我在README中说明这个功能, 这样对原来的功能的破坏性最小, 而且把选项放在data.json对编程的人而言, 修改起来也不难.

希望作者能采纳这个建议, 谢谢.

**Comment by luhaifeng666** [comment]
> 其实我觉得最好的方式也把Text formatting的`Regex flags`选项交给用户, 但是如果放在设置中, 会导致需要太多的设置checkbox, 而且这个功能可能只有少部分人会编程的人会用到.
> 
> 所以我建议, 在data.json中把是否打开Text formatting的Regex flags的选项交给用户自己选择, 然后, 我在README中说明这个功能, 这样对原来的功能的破坏性最小, 而且把选项放在data.json对编程的人而言, 修改起来也不难.
> 
> 希望作者能采纳这个建议, 谢谢.

如果通过代码配置的方式来实现的话，用户在使用的时候就需要手动修改配置文件，并重新构建插件了。这就需要用户下载源码之后再去调整，增加了使用复杂度。
我可以弱化这项配置，比如放到最后，或者设置一个开发者选项的开关，后续如果有类似的配置，可以都规整到开发者选项中去。

**Comment by luhaifeng666** [comment]
支持版本：3.1.0
功能改动：优化配置界面结构，新增开发者选项开关
